services:
  gummybot:
    build: .
    container_name: gummybot
    env_file:
      - .env
    volumes:
      - /srv/data/gummybot:/app/data
      - /srv/data/gummybot/logs:/app/logs
    environment:
      - TZ=America/Chicago
    working_dir: /app
    command: python bot.py
    restart: unless-stopped
